### ISSUE TITLE
lemon weary or lemon tired ..?

### ISSUE THREAD

**Issue by saiTama-max** [python-discord/branding#100]

**Comment by gustavwilliam** [comment]
We do have a sleepy lemoji already. This one:
https://github.com/python-discord/branding/blob/master/emotes/lemoji/dist/lemon_sleepy.png

I'm not sure how this one would be different or what purpose it would serve.

**Comment by lemonsaurus** [comment]
I think the pensive one also communicates weariness.

![image](https://user-images.githubusercontent.com/2098517/99523663-aaf64980-2997-11eb-831f-87a7176d44a9.png)

Also this issue is just not specified clearly enough. Please describe the issue better in the future so we can understand what the request is.

**Comment by saiTama-max** [comment]
oh i didnt notice the sleepy one, that's what i needed
