### ISSUE TITLE
server icon

### ISSUE THREAD

**Issue by grxpee** [python-discord/branding#155]
opinions?

https://user-images.githubusercontent.com/70288471/117106738-aaecd900-ad80-11eb-9316-1e23572134f6.mp4

**Comment by lemonsaurus** [comment]
Hi! Thanks for your contribution.

- Standard server icons should use our regular blurple colors, and the icon must match the relative size of all the existing animations (this one is much smaller). Only special events should use other colors.
- Text is usually a bad idea for a server icon. It's not going to be possible to read any of this stuff at a small resolution.
- The snakes are not aligned correctly in the final frame, and the final frame must always look the same as the first frame in every animation. You should also leave several seconds of no animation at the end of the GIF. See existing animations for examples of this.
- Other factors to consider: The animation must be a GIF, and must be less than 2MB in size. This also limits the quality and duration of the GIF.

It's probably a good idea to start these ideas with an idea instead of just immediately jumping into After Effects, so that we can approve the idea before you put lots of work into the design.

What we're generally looking for is something short, visually fun, and kind of cartoony. Animate the logo using the 12 basic principles of animation, and don't include text. Follow all the steps above.

**Comment by MarkKoz** [comment]
You must consider it in the context in which it will be displayed. It'd be too small to make out most of what's going on.

That being said, I do think the idea of an animation from the logo to some code and then back to the logo is promising. However, it may need some additional "twist" to make it more interesting than just rendering some lines of code.

There's lots of dead space in the current animation, which would have to be filled in. Since it'd be too small to make out details, the code could be arbitrary or even just some thick, broken up lines that look like text.

**Comment by grxpee** [comment]
Yes, i know that was only a little example, i just tried something and not the final animation.

**Comment by gustavwilliam** [comment]
This seems to be pretty stale, so I'm closing this. @grxpee Feel free to reach out to us in `#dev-branding` to discuss your ideas, if there's anything else you'd like to contribute with 😄
