### ISSUE TITLE
Recreate the dice emoji with PyDis colors.

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/branding#68]
We currently have dice emoji in our community, which are used quite actively both by our users and in a seasonalbot feature `.roll`. They look like this:

![image](https://user-images.githubusercontent.com/2098517/93322174-50176900-f813-11ea-941d-33f49edf43e9.png)

It's been suggested that we could rebrand these to have pydis colors, and I think this is a good idea. This issue asks you to create these rebranded pydis dice.

**Comment by MagicTurtle2203** [comment]
A while ago, a member pointed out that the layout of the dice is incorrect. For a standard die, opposite sides should add up to 7. In the picture above, however, 3 and 4 are next to each other rather than on opposite sides. This problem also exists in the other dice. This issue would be a good opportunity to correct the layout of the dice as well.

**Comment by gustavwilliam** [comment]
@lemonsaurus could you assign me this, here on GitHub as well?

@MagicTurtle2203 At least the first design iteration will be flat, eliminating this issue. If this doesn't quite work (which I doubt), we'll make sure to get that right.

**Comment by lemonsaurus** [comment]
Thanks, assigned!
